const browserData = [
    {
        renderingEngine: "Gecko",
        browser: "Firefox 1.0",
        platforms: "Win 98+ / OSX.2+",
        engineVersion: "1.7",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Firefox 1.5",
        platforms: "Win 98+ / OSX.2+",
        engineVersion: "1.8",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Firefox 2.0",
        platforms: "Win 98+ / OSX.2+",
        engineVersion: "1.8",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Firefox 3.0",
        platforms: "Win 2k+ / OSX.3+",
        engineVersion: "1.9",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Camino 1.0",
        platforms: "OSX.2+",
        engineVersion: "1.8",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Camino 1.5",
        platforms: "OSX.3+",
        engineVersion: "1.8",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Netscape 7.2",
        platforms: "Win 95+ / Mac OS 8.6-9.2",
        engineVersion: "1.7",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Netscape Browser 8",
        platforms: "Win 98SE+",
        engineVersion: "1.7",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Netscape Navigator 9",
        platforms: "Win 98+ / OSX.2+",
        engineVersion: "1.8",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.0",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.0",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.1",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.1",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.2",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.2",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.3",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.3",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.4",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.4",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.5",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.5",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.6",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.6",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.7",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.7",
        cssGrade: "A",
    },
    {
        renderingEngine: "Gecko",
        browser: "Mozilla 1.8",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "1.8",
        cssGrade: "A",
    },
    {
        renderingEngine: "Webkit",
        browser: "Safari 1.2",
        platforms: "OSX.3",
        engineVersion: "125.5",
        cssGrade: "A",
    },
    {
        renderingEngine: "Webkit",
        browser: "Safari 1.3",
        platforms: "OSX.3",
        engineVersion: "312.8",
        cssGrade: "A",
    },
    {
        renderingEngine: "Webkit",
        browser: "Safari 2.0",
        platforms: "OSX.4+",
        engineVersion: "419.3",
        cssGrade: "A",
    },
    {
        renderingEngine: "Webkit",
        browser: "Safari 3.0",
        platforms: "OSX.4+",
        engineVersion: "522.1",
        cssGrade: "A",
    },
    {
        renderingEngine: "Webkit",
        browser: "OmniWeb 5.5",
        platforms: "OSX.4+",
        engineVersion: "420",
        cssGrade: "A",
    },
    {
        renderingEngine: "Webkit",
        browser: "iPod Touch / iPhone",
        platforms: "iPod",
        engineVersion: "420.1",
        cssGrade: "A",
    },
    {
        renderingEngine: "Webkit",
        browser: "S60",
        platforms: "S60",
        engineVersion: "413",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera 7.0",
        platforms: "Win 95+ / OSX.1+",
        engineVersion: "7.0",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera 7.5",
        platforms: "Win 95+ / OSX.2+",
        engineVersion: "7.5",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera 8.0",
        platforms: "Win 95+ / OSX.2+",
        engineVersion: "8.0",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera 8.5",
        platforms: "Win 95+ / OSX.2+",
        engineVersion: "8.5",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera 9.0",
        platforms: "Win 95+ / OSX.3+",
        engineVersion: "9.0",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera 9.2",
        platforms: "Win 88+ / OSX.3+",
        engineVersion: "9.2",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera 9.5",
        platforms: "Win 88+ / OSX.3+",
        engineVersion: "9.5",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Opera for Wii",
        platforms: "Wii",
        engineVersion: "9.5",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Nokia N800",
        platforms: "N800",
        engineVersion: "8.5",
        cssGrade: "A",
    },
    {
        renderingEngine: "Presto",
        browser: "Nintendo DS browser",
        platforms: "Nintendo DS",
        engineVersion: "8.5",
        cssGrade: "C/A",
    },
];

export default browserData;
